[tool.poetry]
name = "LARSS IS"
version = "0.1.0"
description = ""
authors = ["MOST HATED"]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "*"
matplotlib = "*"
scipy = "*"
scikit-learn = "*"
tqdm = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
