conf:
  max_mu : 100
  n_samples : 5000
  n_dim : 2 
  n_components : 30
  n_GP_components : 5

hyperparams_dict:
  Mandoline : [3, 6]
  ISE_g_regular : [0, 0.002]
  ISE_g_clip : [0, 0.05]
  ISE_g_estim_clip : [0, 0.05]
  
params:
  max_cov_list : [1, 20]  
  x : ["MCE_g", "ISE_g", "ISE_g_estim"]
  x_hyp: ["ISE_g_regular", "ISE_g_clip", "ISE_g_estim_clip", "Mandoline"]
  y : ["MCE_p"]
  n_tests : 2
  f : "linear"
  model : "linear" 
  n_splits : 1
  log_flag : False

hyperparams_params:
  bw_list : [5, 9]
  beta : 0
  grid_flag : True
  smooth_flag : True
  slice_method : 'clusters'
  
