conf:
  max_mu : 100
  n_samples : 10000
  n_dim : 2 
  n_components : 30
  n_GP_components : 5

params:
  max_cov_list : [30, 35, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
  n_tests : 150
  f : "linear"
  model : "linear" 
  n_splits : 1

methods:
  x_estim : ["ISE_estim"] 
  x_no_estim : ["MCE_g", "ISE"]
  y : ["MCE_p"]

hyp_dict:
  ISE_uni : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  ISE_deg : [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.6, 2, 2.2, 2.5, 3]
  ISE_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99999]
  ISE_estim_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99999]

hyp_params_dict:
  bw_list : [5, "KL"]
  beta : 1
  estim_type : "sklearn"
  KL_flag : True
  KL_plot : False
  df_plots: False
  smooth_flag : True
  clip_thrhold : 0.25
  clip_step : 0.001

  
