conf:
  max_mu : 100
  n_samples : 10000
  n_dim : 4
  n_GM_components : 30
  n_GP_components : 5
  kappa : 0.1
  sigma : 2
  lambda_parent: 2
  lambda_daughter: 100
    

params:
  max_cov_list : [30, 50, 70, 90, 110, 130, 150, 170, 200]
  n_tests : 5
  f : "GMM"
  model : "boosting"
  p_style: "uniform" 
  samples : "GMM"
  n_splits : 1

methods:
  x_estim : ["ISE_estim",] 
  x_no_estim : ["MCE_g", 'Classifier', 'KMM']
  y : ["MCE_p"]

hyp_dict:
  ISE_uni : [0, 1, 10, 0.01, 0.001, 0.0001, 0.0000001, 0.000000001]
  ISE_deg : [0, 0.1, 0.01, 0.001, 2, 10]
  ISE_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99999]
  ISE_estim_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99999]
  KMM : [1000]

hyp_params_dict:
  bw_list : ['scott']
  beta : 0.001
  estim_type : "scipy"
  clip_thrhold : 0.25
  clip_step : 0.001
  confidence : 0.95
  KL_enable : False 
  metrics_plots: True
  smooth_flag : True
  errorbar_flag : False

  
