conf:
  max_mu : 100
  n_samples : 1000
  n_dim : 2 
  n_GM_components : 2
  n_GP_components : 5
  kappa : 0.1
  mu_offspring : 10

params:
  max_cov_list : [0.1, 0.3, 0.5, 1, 1.5, 2, 2.5, 3, 3.5,]
  n_tests : 10
  f : "linear"
  model : "linear" 
  samples : "Thomas"
  n_splits : 1

methods:
  x_estim : ["ISE_estim"] 
  x_no_estim : ["MCE_g"]
  y : ["MCE_p"]

hyp_dict:
  ISE_uni : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  ISE_deg : [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.6, 2, 2.2, 2.5, 3]
  ISE_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99999]
  ISE_estim_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.99999]

hyp_params_dict:
  bw_list : [1,]
  beta : 1
  estim_type : "scipy"
  clip_thrhold : 0.25
  clip_step : 0.001
  confidence : 0.95
  KL_enable : True
  metrics_plots: False
  smooth_flag : True

  
