conf:
  max_mu : 100
  n_samples : 5000
  n_dim : 2 
  n_components : 30
  n_GP_components : 5

hyperparams_dict:
  Mandoline : [2, 7, 13, 16, 19, 22, 26, 27, 30, 33, 35]
  ISE_g_reg_uniform : [0]
  ISE_g_reg_degree : [0, 0.022]
  ISE_g_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
  ISE_g_estim_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
  
params:
  max_cov_list : [1, 15, 30, 45, 70, 100, 125, 150]  
  x : ["MCE_g", "ISE_g", "ISE_g_estim"]
  x_hyp: ["ISE_g_reg_uniform", "ISE_g_reg_degree", "ISE_g_clip", "ISE_g_estim_clip", "Mandoline"]
  y : ["MCE_p"]
  n_tests : 15
  f : "linear"
  model : "linear" 
  n_splits : 1
  log_flag : False

hyperparams_params:
  bw_list : [9]
  beta : 0
  grid_flag : True
  smooth_flag : True
  slice_method : 'clusters'
  
