conf:
  max_mu : 100
  n_samples : 7000
  n_dim : 2 
  n_components : 30
  n_GP_components : 5

hyperparams_dict:
  ISE_g_reg_uniform : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  ISE_g_reg_degree : [0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.6, 2, 2.2, 2.5, 3]
  ISE_g_clip : [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  ISE_g_estim_clip : [0, 0.1,0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  
params:
  max_cov_list : [30, 40, 50, 60, 70, 80, 100, 120, 140] 
  x : ["MCE_g", "ISE_g", "ISE_g_estim"]
  x_hyp: ["ISE_g_reg_degree", "ISE_g_reg_uniform", "ISE_g_clip", "ISE_g_estim_clip"]
  y : ["MCE_p"]
  n_tests : 15
  f : "linear"
  model : "linear" 
  n_splits : 1
  log_flag : False

hyperparams_params:
  bw_list : [5, "KL_LSCV"]
  beta: 1
  smooth_flag : True
  clip_thrhold : 0.25
  clip_step : 0.001

  
